FORMAT: 1A
HOST: http://payment:8880

# PaymentAPI v1 

- version: 1.0

決済を行うAPIです。決済は[Stripe](https://stripe.com/jp)決済プラットフォームで行われます。

主に必要なのは、本サービスに紐づくStripe Customer IDです。

# Group Payment

## Payment [/v1/payment{?stripeToken,customerID,userID,amount,description,email}]

### 決済を行う　[POST]

+ Parameters
    + stripeToken: tok_visa (string) - PublicKeyとカード情報を元に発行されたStripe上のtokenであり、初回決済のときに必要になるものです。`customerID`がない限り`required`です。
    + amount: 4000 (int64) - 料金。単位は**円**です。
    + userID: 3 (int) - 本サービス上のユーザ識別子。
    + customerID: cus_Dn1g1NTijBHzzl (string, optional) - Stripe上の一意なID。2回目からの決済は`stripeToken`を使わず、このフィールドを使って決済をします。`stripeToken`がない限り`required`である。`stripeToken`です。
    + description: "This is desc" (string, optional) - 決済ひとつひとつにつける説明用。主にハンドラテストと統合テストを分けるために付与するものです。
    + email: hogehoge@aho.com (string, optional) - StripeのCustomerとして登録用のメールアドレスです。
+ Response 200 (application/json; charset=UTF-8)
    + Body
                {
                    "error": "",
                    "message": {
                        "customerID": "cus_Dn1g1NTijBHzzl",
                        "amount": 4000,
                        "currency": "JPY",
                        "description": "This is desc",
                        "chargeID": "ch_hnc9Eaieeoau3442Nte"
                    }
                }
+ Response 400 (application/json; charset=UTF-8)
    リクエストフォーマットに関するエラーです。
    + Body
            {
                "error": {
                    "statusCode": 400,
                    "message": "Message about the error",
                }
            }
+ Response 500 (application/json; charset=UTF-8)
    APIのデータベースに関するエラーです。
    + Body
                {
                    "error": {
                        "statusCode": 500,
                        "message": "Message about the error",
                    }
                }
# Group Refund

## Refund [/refund]

### 返金を行う

TODO
